## Simple Attention mechanism without trainable weights

In [1]:
import torch
inputs = torch.tensor(
 [[0.43, 0.15, 0.89], # Your (x^1)
 [0.55, 0.87, 0.66], # journey (x^2)
 [0.57, 0.85, 0.64], # starts (x^3)
 [0.22, 0.58, 0.33], # with (x^4)
 [0.77, 0.25, 0.10], # one (x^5)
 [0.05, 0.80, 0.55]] # step (x^6)
)

In [3]:
input_query = inputs[1]
input_query

tensor([0.5500, 0.8700, 0.6600])

In [4]:
input_1 = inputs[0]
input_1

tensor([0.4300, 0.1500, 0.8900])

In [5]:
0.5500 * 0.43 + 0.87 * 0.15 + 0.66 * 0.89

0.9544

In [6]:
torch.dot(input_1,input_query)

tensor(0.9544)

In [8]:
res = 0
for idx, el in enumerate(inputs[0]):
    res += inputs[0,idx] * input_query[idx]
res

tensor(0.9544)

In [9]:
attn_scores_2 = torch.empty(inputs.shape[0])
for idx, x_i in enumerate(inputs):
    attn_scores_2[idx] = torch.dot(input_query, x_i)
attn_scores_2

tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])

In [10]:
attn_weights_2_temp = attn_scores_2 / attn_scores_2.sum()
attn_weights_2_temp

tensor([0.1455, 0.2278, 0.2249, 0.1285, 0.1077, 0.1656])

In [11]:
def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum(dim=0)

In [12]:
softmax_naive(attn_scores_2)

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [13]:
torch.softmax(attn_scores_2,dim=0)

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [16]:
attn_weights_2 = torch.nn.functional.softmax(attn_scores_2,dim=0)

In [17]:
attn_weights_2

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])

In [23]:
query = inputs[1]
context_vec_2 = torch.zeros(query.shape)
for i, x_i in enumerate(inputs):
    context_vec_2 += attn_weights_2[i] * inputs[i]
context_vec_2

tensor([0.4419, 0.6515, 0.5683])