In [11]:
import torch 
import torch.nn as nn
import numpy as np

In [3]:
model = nn.Sequential(
    nn.Linear(in_features=3, out_features=2, bias=True),
     nn.ReLU(),
    nn.Linear(in_features=2, out_features=4, bias=True),
     nn.ReLU(),

    nn.Linear(in_features=4, out_features=2, bias=True),
     nn.Softmax(dim=1),
)

In [4]:
model

Sequential(
  (0): Linear(in_features=3, out_features=2, bias=True)
  (1): ReLU()
  (2): Linear(in_features=2, out_features=4, bias=True)
  (3): ReLU()
  (4): Linear(in_features=4, out_features=2, bias=True)
  (5): Softmax(dim=1)
)

In [5]:
# input
sample_input = torch.randn(2,3)
sample_input

tensor([[-0.2789, -0.5291, -0.8380],
        [ 0.2069, -2.1425,  0.1868]])

In [6]:
sample_input.shape

torch.Size([2, 3])

In [7]:
output = model(sample_input)
output

tensor([[0.4995, 0.5005],
        [0.5049, 0.4951]], grad_fn=<SoftmaxBackward0>)

In [8]:
a = [1,2,3]
b = [4,5,6]

In [9]:
dot = 0
for x,y in zip(a,b):
    dot += x * y
dot

32

In [10]:
dot2 = 0
for i in range(len(a)):
    dot2 += a[i] * b[i]
dot2

32

In [19]:
a = np.array([1,2,3])
b  = np.array([4,5,6])

In [14]:
np.dot(a,b)

np.int64(32)

In [15]:
a @ b

np.int64(32)

In [16]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

In [17]:
torch.dot(a,b)

tensor(32)

In [18]:
a @b

tensor(32)

In [20]:
xy = list(range(1_000_000))


In [21]:
%timeit [x**2 for x in xy]

113 ms ± 9.51 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
%time np.arange(1_000_000) ** 2

CPU times: total: 15.6 ms
Wall time: 8.4 ms


array([           0,            1,            4, ..., 999994000009,
       999996000004, 999998000001], shape=(1000000,))

In [23]:
logits = torch.tensor([2.3,5.1,0.7])

In [24]:
softmax = torch.nn.functional.softmax(logits, dim=0)
softmax

tensor([0.0567, 0.9319, 0.0114])

In [26]:
torch.argmax(softmax).item()

1

## Batch logits

In [27]:
batch_logits = torch.tensor([[2.3,5.1,0.7],
                             [1.2,0.3,2.5],
                             [0.2,0.6,2.9]
                             ])

In [29]:
probs = torch.nn.functional.softmax(batch_logits, dim=0)
probs

tensor([[0.6871, 0.9810, 0.0622],
        [0.2287, 0.0081, 0.3763],
        [0.0841, 0.0109, 0.5614]])

## Buffers

In [30]:
class MyModel(nn.Module):

    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(10,10)

        # Register a buffer called "scale"
        self.register_buffer("scale", torch.tensor(0.5))

    def forward(self,x):
        return self.linear(x) * self.scale


In [31]:
model = MyModel()

In [40]:
for name, param in model.named_parameters():
    print(name,param)

linear.weight Parameter containing:
tensor([[-0.1681, -0.2519,  0.1956, -0.0977, -0.1365,  0.1255,  0.1655, -0.1217,
          0.0260, -0.2652],
        [ 0.0022, -0.1567, -0.0900,  0.2467,  0.2615, -0.1891,  0.2307, -0.1025,
          0.2431,  0.3056],
        [ 0.0538, -0.0891, -0.2851, -0.1899, -0.0418,  0.1124,  0.2358, -0.0712,
          0.1381,  0.0764],
        [ 0.1073, -0.1976,  0.1630, -0.1381,  0.0624, -0.2458,  0.1372,  0.3090,
         -0.0455, -0.1929],
        [ 0.1549,  0.1372,  0.2735, -0.2394, -0.0102, -0.0677,  0.0734,  0.0466,
         -0.2845,  0.1070],
        [ 0.0020,  0.1992,  0.1073,  0.0526, -0.1449, -0.2937, -0.2751, -0.0818,
          0.2485, -0.1355],
        [-0.0506, -0.1479,  0.3043,  0.1585, -0.0944,  0.1866,  0.1329, -0.2099,
          0.3104, -0.0879],
        [ 0.0572,  0.0781,  0.0789,  0.2333, -0.1269,  0.1331, -0.2694,  0.2270,
         -0.1482,  0.1552],
        [ 0.0910, -0.1228, -0.0772, -0.0321,  0.1506,  0.1767,  0.2576,  0.2737,
          0

In [36]:
model.state_dict().keys()

odict_keys(['scale', 'linear.weight', 'linear.bias'])

In [39]:
for name, buff in model.named_buffers():
    print(name,buff)
 

scale tensor(0.5000)


In [41]:
model.scale

tensor(0.5000)

In [42]:
bn = nn.BatchNorm1d(10)

In [43]:
for name, buff in bn.named_buffers():
    print(name)

running_mean
running_var
num_batches_tracked


In [44]:
torch.save(model.state_dict(), "model.pth")

In [45]:
model.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>